export const services = [
 {slug:"medical-appointments",title:"Medical appointments",short:"Doctor visits, specialist appointments, and the care on your calendar.",icon:"stethoscope",detail:"A ride to your next appointment, with the details arranged ahead of time. Care Ride provides sedan and SUV transportation for eligible, approved non-emergency trips.",examples:["Primary care and specialist visits","Dental and vision appointments","Other approved medical appointments"],note:"Have your appointment time and destination ready when arranging your trip."},
 {slug:"recurring-treatment",title:"Treatment & recurring care",short:"Transportation for dialysis, therapy, and ongoing appointments.",icon:"heart",detail:"When appointments become part of your routine, clear transportation arrangements matter. Ask MAS about scheduling your eligible recurring trips and requesting Care Ride.",examples:["Dialysis appointments","Physical therapy visits","Other approved recurring treatments"],note:"Confirm the dates, pickup times, and return arrangements for each scheduled trip."},
 {slug:"hospital-discharges",title:"Hospital discharges",short:"A comfortable ride to your next approved destination.",icon:"hospital",detail:"Care Ride can help with approved non-emergency transportation following a hospital discharge. Your care team and transportation coordinator can help determine the appropriate ride and timing.",examples:["Approved rides home","Trips to an approved next destination","Coordination around your discharge time"],note:"Ask your discharge team to confirm the appropriate vehicle and transportation arrangements."},
 {slug:"adult-day-programs",title:"Adult day programs",short:"Arranged transportation to the programs that support daily care.",icon:"people",detail:"Getting to a day program starts with the right transportation arrangements. Contact your program, health plan, or dispatch to confirm the booking process and whether Care Ride can serve your trip.",examples:["Approved program transportation","Coordination with program schedules","Pickup and return arrangements"],note:"Some program trips use a different scheduling process. Confirm with your program or plan before booking."},
 {slug:"long-distance",title:"Approved longer trips",short:"Across Long Island and into Manhattan, Queens, Brooklyn, and the Bronx.",icon:"route",detail:"Some appointments take you farther from home. Speak with MAS about approval for your trip, and check with Care Ride dispatch about the route and availability.",examples:["Approved appointments beyond Suffolk County","Specialist visits farther from home","Advance coordination for longer journeys"],note:"Trip approval and vehicle availability must be confirmed for your specific journey."},
 {slug:"sedan-and-suv",title:"Sedan & SUV service",short:"Passenger vehicles for comfortable, non-emergency medical travel.",icon:"car",detail:"Care Ride offers sedan and SUV transportation. Before arranging a trip, describe any mobility or assistance needs to MAS and dispatch so they can confirm the appropriate type of transportation.",examples:["Passenger sedan transportation","SUV transportation","Help understanding vehicle suitability"],note:"For mobility assistance or specialized vehicle needs, confirm the appropriate transportation before scheduling."},
];
export type Service=typeof services[number];
export const faqs=[
 {q:"How do I book a Medicaid ride?",a:"For eligible Medicaid trips in Suffolk County, call MAS at 844-666-6270 or visit medanswering.com. Ask for Care Ride Transportation Corp when choosing your transportation provider. MAS confirms approval and scheduling."},
 {q:"Can I book a ride using the callback form?",a:"The form requests a return call from Care Ride. It does not schedule or confirm a ride. Medicaid transportation must be arranged through the applicable booking process, usually MAS."},
 {q:"Where does Care Ride operate?",a:"Care Ride is based in Shirley and serves all of Long Island (Suffolk and Nassau), plus Manhattan, Queens, Brooklyn, and the Bronx for approved trips. Contact dispatch to confirm your specific pickup location, destination, and availability."},
 {q:"What if I already have a scheduled ride?",a:"Call Care Ride dispatch at (631) 948-3362 with questions about a trip assigned to Care Ride. If you need to change an authorization or transportation arrangement, MAS or your plan may also need to be involved."},
 {q:"What vehicles are available?",a:"Care Ride lists sedan and SUV transportation. If you need mobility assistance or a specialized vehicle, discuss your requirements with MAS and dispatch before scheduling."},
 {q:"Can a family member help arrange the trip?",a:"A family member or caregiver can help you contact MAS or dispatch. Ask MAS what information or permission is needed to arrange transportation on your behalf."},
 {q:"What should I have ready before I call?",a:"Have your pickup location, appointment address, appointment date and time, and return-trip needs ready. MAS may request your Medicaid information. Provide medical or insurance details directly to the appropriate coordinator, not through this website’s callback form."},
];
export const topics=["Booking help","Scheduled ride question","Service area question","Other service question"];
export const callbackTimes=["Any time","Morning","Afternoon"];
