import {callbackDb} from "@/db/callbacks";
import {isStaff} from "@/lib/staff";
import {topics,callbackTimes} from "@/lib/content";
export const dynamic="force-dynamic";
const reply=(data:unknown,status=200)=>Response.json(data,{status,headers:{"Cache-Control":"no-store"}});
function sameOrigin(request:Request){const origin=request.headers.get("origin");return origin===new URL(request.url).origin||origin==="https://care-ride.ali-mohsin12340.chatgpt.site";}
async function payload(request:Request){const text=await request.text();if(text.length>4096)throw new Error("too-large");const data:unknown=JSON.parse(text);if(!data||typeof data!=="object"||Array.isArray(data))throw new Error("invalid-body");return data as Record<string,unknown>;}
const uuid=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
export async function POST(request:Request){if(!sameOrigin(request))return reply({error:"Please submit your request from this website."},403);let data;try{data=await payload(request);}catch{return reply({error:"Please check your request and try again."},400);}if(data.website)return reply({received:true});const name=typeof data.name==="string"?data.name.trim():"";let phone=typeof data.phone==="string"?data.phone.replace(/\D/g,""):"";if(phone.length===11&&phone.startsWith("1"))phone=phone.slice(1);if(!uuid(data.id)||name.length<2||name.length>80||/[\x00-\x1f]/.test(name)||!/^\d{10}$/.test(phone)||!topics.includes(String(data.topic))||!callbackTimes.includes(String(data.time))||data.consent!==true)return reply({error:"Please enter your name, a valid U.S. phone number, and permission to call you."},400);
try{const db=callbackDb();const existing=await db.prepare("SELECT id FROM callback_requests WHERE id = ?").bind(data.id).first();if(existing)return reply({received:true});const now=Date.now();const saved=await db.prepare("INSERT INTO callback_requests (id,name,phone,topic,preferred_time,status,created_at,consent_at) SELECT ?,?,?,?,?, 'new',?,? WHERE (SELECT COUNT(*) FROM callback_requests WHERE phone = ? AND created_at > ?) < 3 ON CONFLICT(id) DO NOTHING").bind(data.id,name,phone,String(data.topic),String(data.time),now,now,phone,now-3600000).run();if(!saved.meta.changes)return reply({error:"You have already sent several requests recently. Please call dispatch for help."},429);return reply({received:true},201);}catch{console.error("Callback request storage failed");return reply({error:"We couldn’t save your request. Please try again or call (631) 948-3362."},503);}}
export async function GET(){if(!await isStaff())return reply({error:"Staff access required."},403);try{const rows=await callbackDb().prepare("SELECT id,name,phone,topic,preferred_time,status,created_at FROM callback_requests ORDER BY created_at DESC LIMIT 100").all();return reply({requests:rows.results});}catch{return reply({error:"The inbox is temporarily unavailable. Please try again."},503);}}
export async function PATCH(request:Request){if(!sameOrigin(request)||!await isStaff())return reply({error:"Staff access required."},403);let data;try{data=await payload(request);}catch{return reply({error:"Invalid request."},400);}if(!uuid(data.id)||!["new","contacted"].includes(String(data.status)))return reply({error:"Invalid request."},400);try{const result=await callbackDb().prepare("UPDATE callback_requests SET status = ? WHERE id = ?").bind(data.status,data.id).run();return result.meta.changes?reply({updated:true}):reply({error:"Request no longer exists."},404);}catch{return reply({error:"The change could not be saved. Please try again."},503);}}
export async function DELETE(request:Request){if(!sameOrigin(request)||!await isStaff())return reply({error:"Staff access required."},403);let data;try{data=await payload(request);}catch{return reply({error:"Invalid request."},400);}if(!uuid(data.id))return reply({error:"Invalid request."},400);try{await callbackDb().prepare("DELETE FROM callback_requests WHERE id = ?").bind(data.id).run();return reply({deleted:true});}catch{return reply({error:"The request could not be deleted. Please try again."},503);}}
